[
    "Namn",
    "Artikelnummer",
    "Färg",
    "Material",
    "Serie",
    "Pris exkl. moms (värde)",
    "Pris exkl. moms (enhet)",
    "Pris inkl. moms (värde)",
    "Pris inkl. moms (enhet)",
    "Längd (värde)",
    "Längd (enhet)",
    "Bredd (värde)",
    "Bredd (enhet)",
    "Höjd (värde)",
    "Höjd (enhet)",
    "Djup (värde)",
    "Djup (enhet)",
    "Diameter (värde)",
    "Diameter (enhet)",
    "Kapacitet (värde)",
    "Kapacitet (enhet)",
    "Volym (värde)",
    "Volym (enhet)",
    "Vikt (värde)",
    "Vikt (enhet)",
    "Data (text)",
    "Kategori (parent)",
    "Kategori (sub)",
    "Produktbild-URL",
    "Produkt-URL",
    "Beskrivning",
    "Extra data"
  ]